---
# ==================================================
# Role: dotfiles
# ==================================================
# dotfiles_repo: https://github.com/afonsoc12/dotfiles
# dotfiles_version: HEAD
# dotfiles_work_tree: "{{ lookup('env','HOME') }}/.config"
# dotfiles_repo_dest: "{{ lookup('env','HOME') }}/.config/dotfiles"
# dotfiles_use_links: true
# dotfiles_extra_zshrc:  # If set, must set dotfiles_use_links to true

# ==================================================
# Role: geerlingguy.mac.homebrew
#   - docs: https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md
# ==================================================
# homebrew_upgrade_all_packages: false
homebrew_taps: []  # don't install default taps to avoid warnings in brew doctor
# homebrew_installed_packages:
#   - git
#   - gh
#   - gpg
#   - iperf3
#   - derailed/k9s/k9s
#   - kubectx
#   - helm
# homebrew_cask_apps:
#   - docker
#   - iterm2
#   - keepassxc
#   - visual-studio-code
#   - google-chrome

# ==================================================
# Role: mas
# ==================================================
# mas_upgrade_all_apps: false
mas_installed_apps: []
# - { id: 409201541,  name: Pages }
# - { id: 409203825,  name: Numbers }
# - { id: 409203825,  name: Keynote }
# - { id: 1475387142, name: Tailscale }

# Uninstall does not work: https://github.com/mas-cli/mas/issues/313
# mas_uninstalled_apps: []

# ==================================================
# Role: python
# ==================================================
# python_pyenv_versions:
#   - 3.9.16
#   - 3.11.2
# python_pyenv_global:
#   - 3.11.2
# python_pip_packages:
#   - pytest
#   - black
#   - isort

# ==================================================
# Role: geerlingguy.mac.dock
#   - docs: https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/dock/README.md
# ==================================================
# dockitems_remove:
# - Launchpad
# - Maps
# - Contacts
# dockitems_persist:
# - name: "iTerm"
#   path: "/Applications/iTerm.app"
#   pos: 1
# - name: "Activity Monitor"
#   path: "/System/Applications/Utilities/Activity Monitor.app"
#   pos: 2
# - name: "Google Chrome"
#   path: "/Applications/Google Chrome.app"
#   pos: 3

# ==================================================
# Role: macos
# ==================================================
# macos_config_files:
# - { src: files/smb/nsmb.conf, dest: /etc, become: true }
# - { src: files/rectangle/com.knollsoft.Rectangle.plist, dest: $HOME/Library/Preferences }
# macos_hosts:
# - {ip: 127.0.0.1, hosts: tst.com}
# macos_add_adobe_hosts: false
# macos_adobe_hosts_file: https://raw.githubusercontent.com/Ruddernation-Designs/Adobe-URL-Block-List/master/hosts

# ==================================================
# Role: git
# ==================================================
# git_global_name: John Doe
# git_global_email: johndoe@test.com
# git_global_signing_key: ~/.ssh/my-ssh-key.pub
# git_global_present_configs:
# - { name: user.email, value: "{{ git_global_email }}" }
# - { name: user.signingkey, value: "{{ git_global_signing_key }}" }
# - { name: pull.rebase, value: "true" }
# - { name: commit.gpgsign, value: "true" }
# - { name: tag.gpgsign, value: "true" }
# - { name: init.defaultBranch, value: master }
# git_global_absent_configs:
# - gpg.format
# git_clone_repos:
# - { repo: git@github.com:<USER>/<REPO>.git, dest: $HOME/git/<REPO> }

# ==================================================
# Role: vscode
# ==================================================
# ide_vscode_extensions:
# - GitHub.copilot
# - GitHub.vscode-pull-request-github
