---
# ==================================================
# Role: dotfiles
# ==================================================
dotfiles_repo: git@github.com:afonsoc12/dotfiles.git
dotfiles_secrets_src: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64636565636636346635326564383961303734613933653937643338306132333865343863396433
          6266333533313464653730663030653763666261336532640a303837323266353564393033333834
          61613038626236396363343061363730383833663361323964613130383861343938333831643737
          3034656537333861610a323934616261383362383065633561336466333030623930366133336562
          33623064633138626431383431306332643532343533313165633235323639386631
dotfiles_repo_dest: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33326236326237613135363133346135356436383838646163303134323533373066373737613232
          6431636363343931313034636137613238633331616434390a613935633833383733306138613132
          38613931373331323164373162386566333033663636613664333063653261353839346435363366
          3931343264326639300a363631363038653432316463646261356531316134353464373732316132
          36373165383232613033623734316338613865323432333930643834393238396562323763613031
          3762383466306533333237393563336430353638316334623839

# ==================================================
# Role: geerlingguy.mac.homebrew
#   - docs: https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md
# ==================================================
homebrew_upgrade_all_packages: true
homebrew_taps:
  - derailed/k9s
  - teamookla/speedtest
homebrew_installed_packages:
  - act
  - argocd
  - cloudflared
  - cmctl
  - etcd
  - exiftool
  - ffmpeg
  - fzf
  - gh
  - ghorg
  - git
  - gpg
  - helm
  - htop
  - influxdb-cli
  - iperf3
  - jq
  - k9s
  - kubectx
  - kubeseal
  - nmap
  - rclone
  - restic
  - rsync
  - speedtest
  - telnet
  - tree
  - wakeonlan
  - yq
homebrew_cask_apps:
  - arduino
  - balenaetcher
  - bruno
  - cyberduck
  - datagrip
  - discord
  - docker
  - drawio
  - google-chrome
  - iterm2
  - keepassxc
  - logi-options-plus
  - nextcloud
  - obsidian
  - openboardview
  - postman
  - pycharm
  - rectangle
  - sigil
  - spotify
  - terraform
  - transmission
  - visual-studio-code
  - vlc
  - whatsapp
  - yubico-yubikey-manager
  - zerotier-one
  - zoom

# ==================================================
# Role: mas
# ==================================================
mas_upgrade_all_apps: true
mas_installed_apps:
  - {name: AmorphousDiskMark, id: 1168254295}
  - {name: Amphetamine, id: 937984704}
  - {name: Disk Speed Test, id: 425264550}
  - {name: GarageBand, id: 682658836}
  - {name: iMovie, id: 408981434}
  - {name: Keynote, id: 409203825}
  - {name: Microsoft Excel, id: 462058435}
  - {name: Microsoft PowerPoint, id: 462062816}
  - {name: Microsoft Word, id: 462054704}
  - {name: MQTT Explorer, id: 1455214828}
  - {name: Numbers, id: 409203825}
  - {name: org.snafu.GeoTag, id: 1465180184}
  - {name: Pages, id: 409201541}
  - {name: Panorama Stitcher Mini, id: 1062350226}
  - {name: Spherical Viewer, id: 1489700765}
  - {name: Surfshark, id: 1437809329}
  - {name: Tailscale, id: 1475387142}
  - {name: Trello, id: 1278508951}
  - {name: WireGuard, id: 1451685025}

# Uninstall does not work: https://github.com/mas-cli/mas/issues/313
mas_uninstalled_apps: []

# ==================================================
# Role: python
# ==================================================
python_pyenv_versions:
  - 3.9.16
  - 3.10.13
  - 3.11.2
python_pyenv_global:
  - 3.11.2
python_pip_packages:
  - ansible
  - black
  - firefly-cli
  - isort
  - oci-cli
  - pipenv
  - pytest
  - requests
  - versioneer

# ==================================================
# Role: geerlingguy.mac.dock
#   - docs: https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/dock/README.md
# ==================================================
dockitems_remove:
  - Launchpad
  - Maps
  - Contacts
  - Notes
  - Freeform
  - Music
  - News
  - Keynote
  - Pages
  - Numbers
  - TV
  - Podcasts
  - App Store

dockitems_persist:
  # TODO
  - name: "iTerm"
    path: "/Applications/iTerm.app"
    pos: 1
  - name: "Activity Monitor"
    path: "/System/Applications/Utilities/Activity Monitor.app"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: KeePassXC
    path: /Applications/KeePassXC.app
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 5
  - name: WhatsApp
    path: /Applications/WhatsApp.app
    pos: 6
  - name: Calendar
    path: /System/Applications/Calendar.app
    pos: 7
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 8
  - name: Preview
    path: /System/Applications/Preview.app
    pos: 9
  - name: Books
    path: /System/Applications/Books.app
    pos: 10
  - name: Reminders
    path: /System/Applications/Reminders.app
    pos: 11

# ==================================================
# Role: macos
# ==================================================
macos_config_files:
  - {src: files/smb/nsmb.conf, dest: /etc, become: true}
  - {src: files/rectangle/com.knollsoft.Rectangle.plist, dest: $HOME/Library/Preferences}
# macos_hosts:
# - {ip: 127.0.0.1, hosts: tst}
# - {ip: 127.0.0.1, hosts: tst2}
# - {ip: 127.0.0.1, hosts: tst3}
# - {ip: 127.0.0.1, hosts: tst4}
macos_add_adobe_hosts: true

# ==================================================
# Role: git
# ==================================================
git_global_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37656631346636643032613363343064386331633935623836656138336132353763373938333862
          3966633733643066346461646162333462613235316135300a346437376433333932393361613138
          63646436306132356433663065326535396538666430333938386436353231626233363135643730
          3961653434366461340a356532623636303231653737373432376238626164343364383364666439
          3933
git_global_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36326534646534633339343639653136323036633932323339376230623363376133663065396263
          6532333835663865393065396362386531653931653433300a623934393562626564626364363231
          35663435363732393930643866613534643835613735383263323431643761653664356161363764
          3365343430333732360a373530303765333666376639613536633165626239323961626335333238
          38623930626231393662626463643363303638613034323130326261353466316334
git_global_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34376264346636336637303239636363333538363532653465326461653966663165303731663737
          3761346332356138353232633232623034323061373138370a613163383063623139313832333963
          32313430623332376630613136663133333535653966333132343461313932343662393564643065
          3738306663386432350a323839353064343462336466313661363633326463343738316631333962
          66633262646636336662646131336538366465313434353766386538303030363130
git_global_present_configs:
  - {name: user.name, value: "{{ git_global_name }}"}
  - {name: user.email, value: "{{ git_global_email }}"}
  - {name: user.signingkey, value: "{{ git_global_signing_key }}"}
  - {name: pull.rebase, value: "true"}
  - {name: commit.gpgsign, value: "true"}
  - {name: tag.gpgsign, value: "true"}
  - {name: init.defaultBranch, value: master}
  - {name: push.autoSetupRemote, value: "true"}

git_global_absent_configs:
  - gpg.format

# ==================================================
# Role: ide
# ==================================================
ide_vscode_extensions:
  - github.vscode-github-actions
  - ms-python.python
  - ms-python.vscode-pylance
  - redhat.ansible
  - redhat.vscode-yaml
  - vscode-icons-team.vscode-icons
