---
- environment:  # noqa name[missing]
    PYENV_ROOT: "{{ python_pyenv_root }}"
  block:
    - name: Install
      import_tasks: install_pyenv.yml
      tags: [install]

    - name: Create folder for PYENV_ROOT
      become: true
      file:
        path: "{{ python_pyenv_root }}"
        state: directory
        mode: "0777"

    - name: Install development packages necessary for building Python
      homebrew:
        name: "{{ python_pyenv_osx_packages }}"
        state: present

    - name: Test pyenv command works
      ansible.builtin.command: pyenv --version
      register: result
      changed_when: false
      failed_when: result.rc != 0 or "pyenv" not in result.stdout

    - name: Install Python {{ python_pyenv_versions | join(' ') }}
      ansible.builtin.command: pyenv install {{ item }} --skip-existing
      register: result
      with_items: "{{ python_pyenv_versions }}"
      changed_when:
        - result.rc == 0
        - result.stdout != ''

    - name: Set pyenv root fact
      command: pyenv root
      register: pyenv_root

    - name: Set pyenv global {{ python_pyenv_global | join(' ') }}
      copy:
        content: "{{ python_pyenv_global | join('\n')  }}"
        dest: "{{ pyenv_root.stdout }}/version"
        mode: "0755"
      when: python_pyenv_global

    - name: Install global Pip packages
      pip:
        name: "{{ item.name | default(item) }}"
        state: present
        version: "{{ item.version | default(omit) }}"
        executable: "{{ pyenv_root.stdout }}/shims/pip"
      loop: "{{ python_pip_packages }}"
